GET http://localhost:3000/api/v1/concerts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNmVhZTc1Yy1lZmIyLTRkODEtOTAzOC0zNWRlMGY0MmU5YjciLCJyb2xlIjoiT1JHQU5JWkVSIiwiaWF0IjoxNzgwNzQ3MTYwLCJleHAiOjE3ODA3NDgwNjB9.WSQfbqah2loNVNIFc156um7cI0nlcfaavxFlNf44JIs
###
GET http://localhost:3000/api/v1/concerts/ad8914cf-3dcb-4fc5-ab0c-1289173e42f9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNmVhZTc1Yy1lZmIyLTRkODEtOTAzOC0zNWRlMGY0MmU5YjciLCJyb2xlIjoiT1JHQU5JWkVSIiwiaWF0IjoxNzgwNzQ3MTYwLCJleHAiOjE3ODA3NDgwNjB9.WSQfbqah2loNVNIFc156um7cI0nlcfaavxFlNf44JIs
###
GET http://localhost:3000/api/v1/concerts/ad8914cf-3dcb-4fc5-ab0c-1289173e42f9/tickets
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNmVhZTc1Yy1lZmIyLTRkODEtOTAzOC0zNWRlMGY0MmU5YjciLCJyb2xlIjoiT1JHQU5JWkVSIiwiaWF0IjoxNzgwNzQ3MTYwLCJleHAiOjE3ODA3NDgwNjB9.WSQfbqah2loNVNIFc156um7cI0nlcfaavxFlNf44JIs
###
GET http://localhost:3000/api/v1/concerts/ad8914cf-3dcb-4fc5-ab0c-1289173e42f9/stock
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNmVhZTc1Yy1lZmIyLTRkODEtOTAzOC0zNWRlMGY0MmU5YjciLCJyb2xlIjoiT1JHQU5JWkVSIiwiaWF0IjoxNzgwNzQ3MTYwLCJleHAiOjE3ODA3NDgwNjB9.WSQfbqah2loNVNIFc156um7cI0nlcfaavxFlNf44JIs
###
POST http://localhost:3000/api/v1/organizer/concerts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNmVhZTc1Yy1lZmIyLTRkODEtOTAzOC0zNWRlMGY0MmU5YjciLCJyb2xlIjoiT1JHQU5JWkVSIiwiaWF0IjoxNzgwNzQ3MTYwLCJleHAiOjE3ODA3NDgwNjB9.WSQfbqah2loNVNIFc156um7cI0nlcfaavxFlNf44JIs

{
    "title": "Pop Music Extravaganza",
    "description": "Join us for an unforgettable night of pop music with top artists from around the world. Experience electrifying performances, great food, and a vibrant atmosphere. Don't miss out on the ultimate pop music festival of the year!",
    "artists": ["The Pop Stars", "Electric Pulse", "The Thunderbolts"],
    "venue": "Madison Square Garden, New York",
    "start_time": "2024-12-15T19:00:00Z",
    "thumbnail_url": "https://example.com/thumbnails/pop-music-extravaganza.jpg",
    "seat_map_svg_url": "https://example.com/seatmaps/pop-music-extravaganza.svg",
    "ticket_types": [
        {
            "name": "General Admission",
            "price": 50.00,
            "total_capacity": 5000,
            "max_per_user": 4
        },
        {
            "name": "VIP",
            "price": 150.00,
            "total_capacity": 1000,
            "max_per_user": 2
        },
        {
            "name": "Backstage Pass",
            "price": 300.00,
            "total_capacity": 100,
            "max_per_user": 1
        }
    ]
}
###
PATCH http://localhost:3000/api/v1/organizer/concerts/0afae19e-d982-4a4a-b065-5d243353497a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNmVhZTc1Yy1lZmIyLTRkODEtOTAzOC0zNWRlMGY0MmU5YjciLCJyb2xlIjoiT1JHQU5JWkVSIiwiaWF0IjoxNzgwNzQ3MTYwLCJleHAiOjE3ODA3NDgwNjB9.WSQfbqah2loNVNIFc156um7cI0nlcfaavxFlNf44JIs

{
    "event_date": "2027-12-15T20:00:00Z"
}
###
PATCH http://localhost:3000/api/v1/organizer/concerts/ad8914cf-3dcb-4fc5-ab0c-1289173e42f9/cancel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNmVhZTc1Yy1lZmIyLTRkODEtOTAzOC0zNWRlMGY0MmU5YjciLCJyb2xlIjoiT1JHQU5JWkVSIiwiaWF0IjoxNzgwNzQ4MTEwLCJleHAiOjE3ODA3NDkwMTB9.mGo5LlmzZ0e8FbBtZR_KPbA0tjvSn4MkfGWyRhf9igY
###
PATCH http://localhost:3000/api/v1/organizer/concerts/ad8914cf-3dcb-4fc5-ab0c-1289173e42f9/publish
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNmVhZTc1Yy1lZmIyLTRkODEtOTAzOC0zNWRlMGY0MmU5YjciLCJyb2xlIjoiT1JHQU5JWkVSIiwiaWF0IjoxNzgwNzQ3MTYwLCJleHAiOjE3ODA3NDgwNjB9.WSQfbqah2loNVNIFc156um7cI0nlcfaavxFlNf44JIs
###
PATCH http://localhost:3000/api/v1/organizer/concerts/ad8914cf-3dcb-4fc5-ab0c-1289173e42f9/restore
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNmVhZTc1Yy1lZmIyLTRkODEtOTAzOC0zNWRlMGY0MmU5YjciLCJyb2xlIjoiT1JHQU5JWkVSIiwiaWF0IjoxNzgwNzQ3MTYwLCJleHAiOjE3ODA3NDgwNjB9.WSQfbqah2loNVNIFc156um7cI0nlcfaavxFlNf44JIs