kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 3000
        protocol: TCP
      - containerPort: 30040
        hostPort: 3004
        protocol: TCP
      - containerPort: 30554
        hostPort: 5540
        protocol: TCP
      - containerPort: 30637
        hostPort: 6379
        protocol: TCP
