POST http://localhost:3000/api/v1/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmMDg4MmNhYS00MGJkLTRlYTYtYjEzMy0zZDRlZDczOWI5OGEiLCJyb2xlIjoiQVVESUVOQ0UiLCJpYXQiOjE3ODEzNDU4NTIsImV4cCI6MTc4MTQzMjI1Mn0.-TxuyDFrUyPxlQ_fZe2XFpJv7Py7GCKaqIJ_SOmdduA
Idempotency-Key: 123e4567-e89b-12d3-a456-426614174000

{
    "paymentMethod": "stripe",
    "data":[
        {
            "concertId": "8a1b2c3d-4e5f-4a6b-8c9d-000000000001",
            "ticketTypeId": "a1111111-1111-4111-8111-111111111111",
            "quantity": 1
        }
    ]
}