GET http://localhost:3000/api/v1/orders/7def66dc-c181-4912-beb1-0c19d5088560/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNmVhZTc1Yy1lZmIyLTRkODEtOTAzOC0zNWRlMGY0MmU5YjciLCJyb2xlIjoiT1JHQU5JWkVSIiwiaWF0IjoxNzgxMTg2NjMxLCJleHAiOjE3ODEyNzMwMzF9.fnEu-iJnN3ediZFlQ_0piwnkJ7oXp0PW4mytGMyD9jA
Idempotency-Key: 123e4567-e89b-12d3-a456-426614174000