GET http://localhost:3000/api/v1/orders/8d676af8-84de-4e1f-8593-ec98c1bbfec9/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNmVhZTc1Yy1lZmIyLTRkODEtOTAzOC0zNWRlMGY0MmU5YjciLCJyb2xlIjoiT1JHQU5JWkVSIiwiaWF0IjoxNzgxMzIxNTI3LCJleHAiOjE3ODE0MDc5Mjd9.S0A2fnybt_u59JMOYGDFTjrhhd16QKsgFCNDERe1ONs
Idempotency-Key: 123e4567-e89b-12d3-a456-426614174000