GET http://localhost:3000/api/v1/tickets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0YWY5MTg3ZS0xNWRkLTQxNjAtYWZmNC04NzRhZWM5MjMxOTQiLCJyb2xlIjoiQVVESUVOQ0UiLCJpYXQiOjE3ODE3ODE5NzcsImV4cCI6MTc4MTg2ODM3N30.RezyKAGb-u-Mx56EmSPbGcbVflfIlbszAHpUNTu98Jk
###
GET http://localhost:3000/api/v1/tickets/tickets/ca400264-eaa4-499d-94ed-0731ced54ca8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0YWY5MTg3ZS0xNWRkLTQxNjAtYWZmNC04NzRhZWM5MjMxOTQiLCJyb2xlIjoiQVVESUVOQ0UiLCJpYXQiOjE3ODE3ODE5NzcsImV4cCI6MTc4MTg2ODM3N30.RezyKAGb-u-Mx56EmSPbGcbVflfIlbszAHpUNTu98Jk
###
GET http://localhost:3000/api/v1/tickets/concerts/8a1b2c3d-4e5f-4a6b-8c9d-000000000001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0YWY5MTg3ZS0xNWRkLTQxNjAtYWZmNC04NzRhZWM5MjMxOTQiLCJyb2xlIjoiQVVESUVOQ0UiLCJpYXQiOjE3ODE3ODE5NzcsImV4cCI6MTc4MTg2ODM3N30.RezyKAGb-u-Mx56EmSPbGcbVflfIlbszAHpUNTu98Jk
###
GET http://localhost:3000/api/v1/checkin/publicKey
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0YWY5MTg3ZS0xNWRkLTQxNjAtYWZmNC04NzRhZWM5MjMxOTQiLCJyb2xlIjoiT1JHQU5JWkVSIiwiaWF0IjoxNzgxODYzODkwLCJleHAiOjE3ODE5NTAyOTB9.eJ8LCO3dtBwqDE76y7LTXcPJJoJ8F32IgbT6S-Y4u78