POST http://localhost:3000/api/v1/auth/sign-in
Content-Type: application/json

{
  "email": "nichi@example.com",
  "password": "123456"
}
###
POST http://localhost:3000/api/v1/auth/sign-in
Content-Type: application/json

{
  "email": "newuser@example.com",
  "password": "123456"
}

###
POST http://localhost:3000/api/v1/auth/sign-up
Content-Type: application/json

{
  "email": "nichi@example.com",
  "password": "123456",
  "fullName": "Nichi"
}

###
POST http://localhost:3000/api/v1/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNmVhZTc1Yy1lZmIyLTRkODEtOTAzOC0zNWRlMGY0MmU5YjciLCJyb2xlIjoiT1JHQU5JWkVSIiwiaWF0IjoxNzgwNzM4NjA4LCJleHAiOjE3ODEzNDM0MDh9.2L_0L3Vsb3FQ1ZOGLS-pa9noJSM8RqtDrGPnhUjkpgI"
}

###
PATCH http://localhost:3000/api/v1/organizer/users/62d6634d-8d9f-4e32-ac8e-5e77037a72b2/role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNmVhZTc1Yy1lZmIyLTRkODEtOTAzOC0zNWRlMGY0MmU5YjciLCJyb2xlIjoiT1JHQU5JWkVSIiwiaWF0IjoxNzgwNzM3Mzk2LCJleHAiOjE3ODA3MzgyOTZ9.gWDzMTppYL3C179ZapG0wrKcjoaO7a1QPDkTBFBTR60

{
  "role": "ORGANIZER"
}

###
PATCH http://localhost:3000/api/v1/organizer/users/62d6634d-8d9f-4e32-ac8e-5e77037a72b2/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNmVhZTc1Yy1lZmIyLTRkODEtOTAzOC0zNWRlMGY0MmU5YjciLCJyb2xlIjoiT1JHQU5JWkVSIiwiaWF0IjoxNzgwNzM3Mzk2LCJleHAiOjE3ODA3MzgyOTZ9.gWDzMTppYL3C179ZapG0wrKcjoaO7a1QPDkTBFBTR60

{
  "status": "BANNED"
}

###
GET http://localhost:3000/api/v1/organizer/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNmVhZTc1Yy1lZmIyLTRkODEtOTAzOC0zNWRlMGY0MmU5YjciLCJyb2xlIjoiT1JHQU5JWkVSIiwiaWF0IjoxNzgwNzM3Mzk2LCJleHAiOjE3ODA3MzgyOTZ9.gWDzMTppYL3C179ZapG0wrKcjoaO7a1QPDkTBFBTR60

###
GET http://localhost:3000/api/v1/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNmVhZTc1Yy1lZmIyLTRkODEtOTAzOC0zNWRlMGY0MmU5YjciLCJyb2xlIjoiT1JHQU5JWkVSIiwiaWF0IjoxNzgwNzM3Mzk2LCJleHAiOjE3ODA3MzgyOTZ9.gWDzMTppYL3C179ZapG0wrKcjoaO7a1QPDkTBFBTR60
